chalupa/urls.py
from django.urls import path
from . import views
#from .views import RoomListView, BookingView, RoomDetailView

app_name = 'chalupa'
urlpatterns = [
    path('', views.index, name='index'),
    path('pokoje/', views.RoomListView.as_view(), name='RoomListView'),
    path('pokoj/<int:pk>', views.RoomDetailView.as_view(), name='room-detail'),
    path('rezervovat/', views.BookingView.as_view(), name='BookingView'),
    path('rezervovat/upravit/<booking_id>', views.booking_edit, name='booking-edit'),
    path('rezervovat/zrusit/<pk>', views.BookingCancelView.as_view(), name='BookingCancelView'),
    path('galerie/', views.gallery, name='Gallery'),
    path('galerie/pridat', views.add_image, name='AddPhoto'),
    path('galerie/<str:pk>', views.view_image, name='Image'),

]

quickstart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chalupa.urls')),
    path('', RedirectView.as_view(url='chalupa/')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns.append(path('', include('cms.urls')))

chalupa/models.py
from django.db import models
from django.conf import settings
# from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse, reverse_lazy

# Create your models here.

def attachment_path(instance, filename):
    return "pokoj/" + str(instance.room.id) + "/attachments/" + filename


def image_path(instance, filename):
    return "pokoj/" + filename


'''class BookingObject(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name', help_text='Chalupa Stoklaska')
    image = models.ImageField(upload_to=image_path, blank=True, null=True, verbose_name='Image')
    address = models.CharField(max_length=100, verbose_name='Address', help_text='Ludvíkov 81')
    capacity = models.PositiveIntegerField(default='12', help_text='How many guests can be housed?')
    price_per_night = models.PositiveIntegerField(default='1000', verbose_name='Price per night',
                                                  help_text='The cost per one night')
    private_bathroom = models.BooleanField(verbose_name='Private bathroom',
                                           help_text='Does the guesthouse have a private bathroom?')
    number_of_rooms = models.PositiveIntegerField(default='3', verbose_name='Number of rooms',
                                                  help_text='How many rooms for guests does it have?')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]'''

class Room(models.Model):
    name = models.CharField(max_length=20, verbose_name='Room name', help_text='Enter the room name')
    image = models.ImageField(upload_to=image_path, blank=True, null=True, verbose_name="Image")
    capacity = models.PositiveIntegerField(help_text='Enter the capacity of the room (extra beds included)', default='3')
    extra_bed = models.BooleanField(default=False)
    #booking_object = models.ForeignKey(BookingObject, on_delete=models.CASCADE)

    class Meta:
        ordering = ["name"]

    '''def get_absolute_url(self):
        return reverse('RoomDetailView', args=[str(self.id)])'''

    def __str__(self):
        return f'{self.name}, pro {self.capacity} osoby'


class Booking(models.Model):
    number_of_guests = models.IntegerField(default=1)
    check_in = models.DateField(verbose_name='Od', default='')
    check_out = models.DateField(verbose_name='Do', default='')
    note = models.TextField(max_length=2000, null=True, blank=True)
    #booking_object = models.ForeignKey(BookingObject, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, help_text='Enter the name and surname', on_delete=models.CASCADE,
                             default='')

    class Meta:
        ordering = ["user"]

    def __str__(self):
        return f'{self.user}, od {self.check_in} do {self.check_out}, {self.number_of_guests} hostů'

    def get_booking_cancel_url(self):
        return reverse_lazy('chalupa:BookingCancelView', args=[self.pk, ])

    @property
    def get_html_url(self):
        url = reverse('chalupa:booking-edit', args=(self.id,))
        return f'<a href="{url}"> Rezervováno od {self.user} </a>'


class Category(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False)

    def __str__(self):
        return self.name


class Attachment(models.Model):
    title = models.CharField(max_length=100, verbose_name="Title")
    #last_update = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(null=False, blank=False)
    #booking_object = models.ForeignKey(BookingObject, on_delete=models.CASCADE)
    #room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        order_with_respect_to = 'title'

chalupa/forms.py
from django import forms
from datetime import datetime, timedelta, date
from django.forms import ModelForm, DateInput
from calendar import HTMLCalendar
from .models import Booking


class AvailabilityForm(forms.Form):
    check_in = forms.DateField(required=True, input_formats=['%Y-%m-%d', ])
    check_out = forms.DateField(required=True, input_formats=['%Y-%m-%d', ])
    number_of_guests = forms.IntegerField(required=True)
    note = forms.CharField(required=False, widget=forms.Textarea)
    def print_form(self):
        pass


class BookingForm(ModelForm):
    class Meta:
        model = Booking
        widgets = {
            'check_in': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'check_out': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = ('check_in', 'check_out', 'number_of_guests', 'note')

    def __init__(self, *args, **kwargs):
        super(BookingForm, self).__init__(*args, **kwargs)
        self.fields['check_in'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['check_out'].input_formats = ('%Y-%m-%dT%H:%M',)


class Calendar(HTMLCalendar):
    def __init__(self, year=None, month=None):
        self.year = year
        self.month = month
        super(Calendar, self).__init__()

    # formats a day as a td
    # filter bookings by day
    def formatday(self, day, bookings):
        bookings_per_day = bookings.filter(check_in__day=day)
        d = ''
        for booking in bookings_per_day:
            d += f'<li class="list-group-item"> {booking.get_html_url} </li>'

        if day != 0:
            return f"<td><span class='date'>{day}</span><ul> {d} </ul></td>"
            # if date.today() == date(self.year, self.month, day):
            # return f"<td class='today'><div class='d-flex justify-content-between'><span class='date'>{day}</span>{Booking.get_date(self, self.year, self.month, day)}</div><ul> {d} </ul></td>"
            # return f"<td><div class='d-flex justify-content-between'><span class='date'>{day}</span>{Booking.get_date(self, self.year, self.month, day)}</div><ul> {d} </ul></td>"
        return '<td></td>'

    # formats a week as a tr
    def formatweek(self, week, bookings):
        w = ''
        for d, weekday in week:
            w += self.formatday(d, bookings)
        return f'<tr> {w} </tr>'

    # formats a month as a table
    # filter bookings by year and month
    def formatmonth(self, withyear=True):
        bookings = Booking.objects.filter(check_in__year=self.year, check_in__month=self.month)

        cal = f'<table border="0" cellpadding="0" cellspacing="0" class="calendar">\n'
        cal += f'{self.formatmonthname(self.year, self.month, withyear=withyear)}\n'
        cal += f'{self.formatweekheader()}\n'
        for week in self.monthdays2calendar(self.year, self.month):
            cal += f'{self.formatweek(week, bookings)}\n'
        return cal

chalupa/views.py
from django.http import request, HttpResponseRedirect
from datetime import datetime, date, timedelta
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.views import generic
from django.views.generic import ListView, FormView, View, DetailView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.utils.safestring import mark_safe

from .models import Room, Booking, Attachment, Category
from .forms import AvailabilityForm, Calendar, BookingForm
import calendar
from chalupa.booking_functions.availability import availability


# Create your views here.


# domovská stránka
def index(request):
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=context)


class RoomListView(generic.ListView):
    model = Room
    context_object_name = 'room_list'
    template_name = 'chalupa/room_list.html'


# detail pokoje
'''class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        name = self.kwargs.get('name', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(name=name)

        if len(room_list) > 0:
            room = room_list[0]
            room_name = dict(room.room_names).get(room.name, None)
            context = {
                'room_name': room_name,
                'form': form
            }
            return render(request, 'room_detail_view.html', context)
        else:
            return HttpResponse('Tento pokoj neexistuje')'''


class RoomDetailView(generic.DetailView):
    model = Room
    context_object_name = 'room_detail'
    template_name = 'chalupa/room_detail.html'

    # Toto je nadbytečné
    '''def post(self, request, *args, **kwargs):
        name = self.kwargs.get('name', None)
        room_list = Room.objects.filter(name=name)
        form = AvailabilityForm(request.POST)
        if availability(data['check_in'], data['check_out']):
            bookings = Booking.objects.create(
                user=self.request.user,
                check_in=data['check_in'],
                check_out=data['check_out'],
            )
            bookings.save()
            return HttpResponse(bookings)
        else:
            return HttpResponse('Tenhle termín je už rezervovaný')
        form.print_form()
        return super().form_valid(form)'''


# rezervace termínu
class BookingView(LoginRequiredMixin, FormView, ListView):
    form_class = AvailabilityForm
    template_name = 'chalupa/booking_view.html'

    def form_valid(self, form):
        data = form.cleaned_data
        if availability(data['check_in'], data['check_out']):
            booking = Booking.objects.create(
                user=self.request.user,
                check_in=data['check_in'],
                check_out=data['check_out'],
                number_of_guests=data['number_of_guests'],
                note=data['note'], )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse('Tento termín už je rezervovaný')
        # form.print_form()
        # return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)

        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Booking.objects.all()
            return booking_list
        else:
            booking_list = Booking.objects.filter(user=self.request.user)
            return booking_list


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def booking_edit(request, booking_id=None):
    instance = Booking()
    if booking_id:
        instance = get_object_or_404(Booking, pk=booking_id)
    else:
        instance = Booking()

    form = BookingForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('chalupa:BookingView'))
    return render(request, 'chalupa/booking_edit.html', {'form': form})


class BookingCancelView(LoginRequiredMixin, DeleteView):
    model = Booking
    template_name = 'chalupa/booking_cancel.html'
    success_url = reverse_lazy('chalupa:BookingView')

# galerie
def gallery(request):
    category = request.GET.get('category')
    if category == None:
        images = Attachment.objects.all()
    else:
        images = Attachment.objects.filter(category__name=category)

    categories = Category.objects.all()
    context = {'categories': categories, 'images': images}
    return render(request, 'chalupa/gallery.html', context)


def view_image(request, pk):
    image = Attachment.objects.get(id=pk)
    return render(request, 'chalupa/gallery.html', {'image': image})


def add_image(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        data = request.POST
        image = request.FILES.get('image')

        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(title=data['category_new'])
        else:
            category = None

        attachment = Attachment.objects.create(
            title=data['title'],
            category=category,
            image=image,
        )

        return redirect('chalupa:Gallery')

    context = {'categories': categories}
    return render(request, 'chalupa/image_add.html', context)


'''class CalendarView(generic.ListView):
    model = Booking
    template_name = 'booking_view.html'
    '''

chalupa/templates/chalupa/booking_cancel.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<body style="background-color: rgba(62,29,29,0.1);">
    <div class="container">
            <h4 class="text-center pt-3">Opravdu chcete zrušit Vaši rezervaci?</h4>
            <p class="text-center">{{ booking }}</p>
        <div class="d-grid gap-2 d-md-flex justify-content-center">
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Ano, zrušit"></form>
            </form>
        </div>
    </div>
</body>
{% endblock %}

chalupa/templates/chalupa/booking_edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Rezervace
{% endblock %}
{% block content %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Stoklaska</title>
        <!-- Main StyleSheet -->
        <link rel="stylesheet" href="{% static 'chalupa/css/calendar.css' %}">
    </head>
<body style="background-color: rgba(62,29,29,0.1)">
    <div class="clearfix">
        <a class="btn btn-outline-dark left" href="{% url 'chalupa:BookingView' %}"> Kalendář </a>
    </div>

    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
            <tr>
                <td colspan="2">
                    <button type="submit" class="btn btn-outline-dark right">Potvrdit</button>
                </td>
            </tr>
        </table>
    </form>
</body>
{% endblock %}

chalupa/templates/chalupa/booking_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Rezervace
{% endblock %}
{% block content %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Stoklaska</title>
        <!-- Main StyleSheet -->
        <link rel="stylesheet" href="{% static 'chalupa/css/calendar.css' %}">
    </head>

    <div class="clearfix">
        <a class="btn btn-outline-dark left" href="{% url 'chalupa:BookingView' %}"> Kalendář </a>
    </div>

    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
            <tr>
                <td colspan="2">
                    <button type="submit" class="btn btn-outline-dark right"> Submit</button>
                </td>
            </tr>
        </table>
    </form>

{% endblock %}

chalupa/templates/chalupa/booking_view.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Stoklaska</title>
        <!-- Main StyleSheet -->
        <link rel="stylesheet" href="{% static 'chalupa/css/calendar.css' %}">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
    </head>
    <body style="background-color: rgba(62,29,29,0.1)">
    <div class="container m-4">
        <div class="row">
            <div class="col-md-4">
                <div class="card" style="background-color: rgba(62,29,29,0)">
                    <div class="card-header">
                        <b>Rezervovat</b>
                    </div>
                    <table>
                        <div class="form-group">
                            <form action="" method="POST" class="m-3" enctype="multipart/form-data">
                                {{ form.as_table }}
                                {% csrf_token %}
                                <button type="submit" class="mb-3">Rezervovat</button>
                            </form>
                        </div>
                    </table>
                </div>
                <div class="card mt-4" style="background-color: rgba(62,29,29,0)">
                    <div class="card-header">
                        <b>Seznam rezervací</b>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for booking in booking_list %}
                            <li class="list-group-item">{{ booking }}
                                <a href="{{ booking.get_booking_cancel_url }}"
                                   class="btn btn-outline-dark btn-sm right">Zrušit</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-8">
                <div class="clearfix">
                    <a class="btn btn-light left" href="{% url 'chalupa:BookingView' %}?{{ prev_month }}">
                        Předchozí
                        měsíc </a>
                    <a class="btn btn-light right" href="{% url 'chalupa:BookingView' %}?{{ next_month }}"> Další
                        měsíc </a>
                </div>
                {{ calendar }}
            </div>
        </div>
    </div>

    </body>


    <!-- <form action="" method="POST">
        <h2>Rezervace termínu</h2>
        { form.as_p }}
        { csrf_token %}
        <button type="submit">Rezervovat</button>
    </form>
    <br>
    <div class="clearfix">
        <a class="btn btn-info left" href="{ url 'chalupa:BookingView' %}?{{ prev_month }}"> Předchozí měsíc </a>
        <a class="btn btn-info right" href="{ url 'chalupa:BookingView' %}?{{ next_month }}"> Další měsíc </a>
    </div>
    <div>{ calendar }}</div>-->


    <!--<div class="col-md-6">
    <div class="clearfix">
        <a class="btn btn-outline-dark left" href="{ url 'chalupa:BookingView' %}?{ prev_month }}">
            Předchozí měsíc </a>
        <a class="btn btn-outline-dark right" href="{ url 'chalupa:BookingView' %}?{ next_month }}">
            Další
            měsíc </a>
    </div>
    <div>{ calendar }}</div>
</div>
<div class="col-md-3">
    <form action="" method="POST">
        <h2>Rezervace termínu</h2>
        { form.as_p }}
        { csrf_token %}
        <button type="submit">Rezervovat</button>
    </form>
</div>-->

{% endblock %}

chalupa/templates/chalupa/gallery.html
{% extends "base.html" %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Galerie</title>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplelightbox/2.7.0/simple-lightbox.css"
              integrity="sha512-8WAX0xL/cHZ38RXoX2gtuqkAwmDVAzGwoFVmHvn46IDHGWOjTHx0vcl9OapNrfOzpFtql0SNkv+0y0b5Fm8ZkA=="
              crossorigin="anonymous"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/simplelightbox/2.7.0/simple-lightbox.min.js"
                integrity="sha512-ZajFBgnksNp8Rj+AbmYe8ueOu45HiSjtf3QpqnRbHlq719m6VK0FkbYIqQ8wEnlVuJ1i9pC+z6Z9ewmDnUTMCg=="
                crossorigin="anonymous"></script>

        <style>
            .img-thumbnail {
                height: 200px;
            }

            .list-group-item a {
                text-decoration: none;
                color: black;
            }

            img.hover-shadow {
                transition: 0.3s;
            }
        </style>
    </head>
    <body style="background-color: rgba(62,29,29,0.1)">
    <div class="container m-4">
        <div class="row">
            <div class="col-md-3">
                <div class="card" style="background-color: rgba(62,29,29,0)">
                    <div class="card-header">
                        Kategorie
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'chalupa:Gallery' %}">Všechny</a>
                        </li>
                        {% for category in categories %}
                            <li class="list-group-item">
                                <a href="{% url 'chalupa:Gallery' %}?category={{ category.name }}">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                        <li class="list-group-item">
                            <a href="{% url 'chalupa:AddPhoto' %}" class="btn btn-outline-dark btn-sm">Přidat</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    {% for image in images %}
                        <div class="col-md-4 my-2 photo_gallery">
                            <a href="{{ image.image.url }}">
                                <img src="{{ image.image.url }}"
                                     alt="{{ image.title }}" class="img-thumbnail img-fluid"
                                     onclick="openModal();currentSlide(1)" class="hover-shadow">
                            </a>
                        </div>
                    {% empty %}
                        <h2 class="text-center">Na fotkách pracujeme ...</h2>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script>
        let gallery = new SimpleLightbox('.photo_gallery a');
    </script>
    </body>
{% endblock %}

chalupa/templates/chalupa/image_add.html
{% extends "base.html" %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Galerie</title>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
    </head>

    <div class="m-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <a href="{% url 'chalupa:Gallery' %}" class="btn btn-outline-dark my-3">Zpět</a>
                    <div class="card">
                        <form method="POST" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group m-3">
                                <label>Název</label>
                                <input required name="title" type="text" placeholder="Zadejte název"
                                       class="form-control">
                            </div>
                            <div class="form-group m-3">
                                <label>Vyberte kategorii</label>
                                <select name="category" class="form-control">
                                    <option value="none">Vyberte kategorii</option>
                                    {% for category in categories %}
                                        <option value="{{ category.id }}">{{ category.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group m-3">
                                <label>Vytvořit novou kategorii</label>
                                <input name="category_new" type="text" placeholder="Zadejte nový název kategorie"
                                       class="form-control">
                            </div>
                            <div class="form-group m-3">
                                <label>Nahrát obrázek</label>
                                <input required name="image" type="file" class="form-control-file">
                            </div>
                            <button type="submit" class="btn btn-outline-dark m-3">Potvrdit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

chalupa/templates/chalupa/room_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Detail pokoje</title>
        <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

        <!-- Main StyleSheet -->
        <link rel="stylesheet" href="{% static '/chalupa/css/detail.css' %}">
    </head>

    <!-- Hlavní obsah -->
    <body style="background-color: rgba(62,29,29,0.1)">
    <div class="content mb-3">

        <!-- Fotka pokoje -->
        <div class="image col-md-8">
            {% if room_detail.image %}
                <a href="{{ room_detail.image.url }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ room_detail.image.url }}" class="pt-3 m-3" alt="Picture of the room">
                </a>
            {% endif %}
            <!-- src="http://www.stoklaska.cz/obrazky/fotoalbum/2011-09-interier-chalupy/1-inter-stoklas.jpg">-->
        </div>

        <!-- Detail pokoje -->
        <div class="room col-md-3" style="padding: 70px">

            <!-- Div 1: Šipka zpět na seznam pokojů -->
            <div class="home">
                <a href="{% url 'chalupa:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Zpět</i></a>
            </div>

            <!-- Div 2: Informace o pokoji -->
            <div class="room-info" style="color: black">
                <h1>{{ room_name }}</h1>
                <p>{{ room_detail.name }}</p>
                <p>Kapacita: Pro {{ room_detail.capacity }} osoby</p>
                <p>Přistýlka: {% if room_detail.extra_bed %} Ano {% else %} Ne {% endif %}</p>
            </div>

            <!-- Div 3: Rezervace
            <form id="booking-form" action="" method="POST">

                { csrf_token %}

                <!- Input Div ->
                <div class="input-div">
                    <label for="id_check_in">Od : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!- Input Div ->
                <div class="input-div">
                    <label for="id_check_out">Do : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>

                <!- Input Div ->
                <div class="input-div">
                    <button type="submit">Rezervovat</button>
                </div> -->

            </form>

        </div> <!-- Konec detailu pokoje -->

    </div> <!-- Konec hlavního obsahu -->
    </body>

{% endblock %}

chalupa/templates/chalupa/room_list.html
<!--<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>Pokoje</title>
</head>
<body>
    <h1>Pokoje</h1>
    { for room in room_list %}
    <h2>{ room }}</h2>
    { endfor %}
</body>
</html>
-->
{% extends "base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="cs">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stoklaska</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'chalupa/css/rooms.css' %}">
</head>

<body style="background-color: rgba(62,29,29,0.1)">
    <!-- Brand -->
    <!--<h1 id="brand" style="color: #521b18; text-shadow: 2px 2px 0 #000">Chalupa Stoklaska - pokoje </h1> -->

    <!-- Main Content -->
    <div class="content" style="padding-top: 80px">
        {% for room in room_list %}
        <div class="room" style="border-radius: 0px; background-color: #521b18; margin: 0px; padding: 1rem">
            <a href="{% url 'chalupa:room-detail' room.pk %}">
                {% if room.image %}
                <img src="{{ room.image.url }}">
                {% endif %}
                <h2>{{room.name}}</h2>
                <p> Pro {{ room.capacity }} osoby </p>
            </a>
        </div>
        {% endfor %}
    </div>
</body>

</html>>
{% endblock %}